export const BrandsData = [
  {
    Name: "PARIGI",
    Description: "<p>test</p>",
    ManufacturerTemplateId: 1,
    AvailableManufacturerTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "parigi",
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    ManufacturerProductSearchModel: {
      ManufacturerId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 4,
    CustomProperties: {},
  },
  {
    Name: "Laura Ashley",
    Description: null,
    ManufacturerTemplateId: 1,
    AvailableManufacturerTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "laura-ashley",
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    ManufacturerProductSearchModel: {
      ManufacturerId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 5,
    CustomProperties: {},
  },
];
