export const CatalogData = [
  {
    Name: "Watch",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "watch",
    ParentCategoryId: 0,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Watch",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 17,
    CustomProperties: {},
  },
  {
    Name: "Bag",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "bag",
    ParentCategoryId: 0,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Bag",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 18,
    CustomProperties: {},
  },
  {
    Name: "Ali Express",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "ali-express",
    ParentCategoryId: 0,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: false,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 19,
    CustomProperties: {},
  },
  {
    Name: "Women's Handbags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "womens-handbags",
    ParentCategoryId: 19,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 22,
    CustomProperties: {},
  },
  {
    Name: "Waist Packs",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "waist-packs",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Waist Packs",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 23,
    CustomProperties: {},
  },
  {
    Name: "Shoulder Bags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "shoulder-bags",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Shoulder Bags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 24,
    CustomProperties: {},
  },
  {
    Name: "Messenger Bags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "messenger-bags",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Messenger Bags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 25,
    CustomProperties: {},
  },
  {
    Name: "Clutches",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "clutches",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Clutches",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 26,
    CustomProperties: {},
  },
  {
    Name: "Chest Bags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "chest-bags",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Chest Bags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 27,
    CustomProperties: {},
  },
  {
    Name: "Top-Handle Bags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "top-handle-bags",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Top-Handle Bags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 28,
    CustomProperties: {},
  },
  {
    Name: "Crossbody Bags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "crossbody-bags",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Crossbody Bags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 29,
    CustomProperties: {},
  },
  {
    Name: "Evening Bags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "evening-bags",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Evening Bags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 30,
    CustomProperties: {},
  },
  {
    Name: "Tote Bags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "tote-bags",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Tote Bags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 31,
    CustomProperties: {},
  },
  {
    Name: "Hobo Bags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "hobo-bags",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Hobo Bags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 32,
    CustomProperties: {},
  },
  {
    Name: "Wristlets",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "wristlets",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Wristlets",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 33,
    CustomProperties: {},
  },
  {
    Name: "Fashion Backpacks",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "fashion-backpacks",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Fashion Backpacks",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 34,
    CustomProperties: {},
  },
  {
    Name: "Satchels",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "satchels",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Satchels",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 35,
    CustomProperties: {},
  },
  {
    Name: "Mini Bags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "mini-bags",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Mini Bags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 36,
    CustomProperties: {},
  },
  {
    Name: "Computer & Office",
    Description: "<div>\r\n<div>7</div>\r\n</div>",
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "computer-office",
    ParentCategoryId: 19,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Computer & Office",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 37,
    CustomProperties: {},
  },
  {
    Name: "Telephone Headsets",
    Description: "<div>\r\n<div>5091005</div>\r\n</div>",
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "telephones-accessories",
    ParentCategoryId: 37,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Computer & Office >> Telephone Headsets",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 38,
    CustomProperties: {},
  },
  {
    Name: "USB Gadgets",
    Description: "<div>\r\n<div>7171</div>\r\n</div>",
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "usb-gadgets",
    ParentCategoryId: 37,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Computer & Office >> USB Gadgets",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 40,
    CustomProperties: {},
  },
  {
    Name: "Keyboards",
    Description: "<div>\r\n<div>70802</div>\r\n</div>",
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "keyboards",
    ParentCategoryId: 37,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Computer & Office >> Keyboards",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 42,
    CustomProperties: {},
  },
  {
    Name: "Mouse",
    Description: "<div>\r\n<div>70805</div>\r\n</div>",
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "mouse",
    ParentCategoryId: 37,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Computer & Office >> Mouse",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 43,
    CustomProperties: {},
  },
  {
    Name: "Game",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "game-2",
    ParentCategoryId: 19,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Game",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 44,
    CustomProperties: {},
  },
  {
    Name: "Gamepads",
    Description: "<div>\r\n<div>200001103</div>\r\n</div>",
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "gamepads",
    ParentCategoryId: 44,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Game >> Gamepads",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 45,
    CustomProperties: {},
  },
  {
    Name: "Joysticks",
    Description: "<div>\r\n<div>200001104</div>\r\n</div>",
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "joysticks",
    ParentCategoryId: 44,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Game >> Joysticks",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 46,
    CustomProperties: {},
  },
  {
    Name: "Chargers",
    Description: "<div>\r\n<div>200003086</div>\r\n</div>",
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "chargers",
    ParentCategoryId: 44,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Game >> Chargers",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 47,
    CustomProperties: {},
  },
  {
    Name: "Cables",
    Description: "<div>\r\n<div>200003088</div>\r\n</div>",
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "cables",
    ParentCategoryId: 44,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Game >> Cables",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 48,
    CustomProperties: {},
  },
  {
    Name: "USB Receiver Adapter",
    Description: "<div>\r\n<div>200005122</div>\r\n</div>",
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "usb-receiver-adapter",
    ParentCategoryId: 44,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Game >> USB Receiver Adapter",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 49,
    CustomProperties: {},
  },
  {
    Name: "Phones & Telecommunications",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "phones-telecommunications",
    ParentCategoryId: 19,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Phones & Telecommunications",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 50,
    CustomProperties: {},
  },
  {
    Name: "Communication Cables",
    Description: "<div>\r\n<div>50912</div>\r\n</div>",
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "communication-cables",
    ParentCategoryId: 50,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb:
      "Ali Express >> Phones & Telecommunications >> Communication Cables",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 51,
    CustomProperties: {},
  },
  {
    Name: "Mobile Phone Batteries",
    Description: "<div>\r\n<div>52804</div>\r\n</div>",
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "mobile-phone-batteries",
    ParentCategoryId: 50,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb:
      "Ali Express >> Phones & Telecommunications >> Mobile Phone Batteries",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 52,
    CustomProperties: {},
  },
  {
    Name: "Mobile Phone Flex Cables",
    Description: "<div>\r\n<div>5904001</div>\r\n</div>",
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "mobile-phone-flex-cables",
    ParentCategoryId: 50,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb:
      "Ali Express >> Phones & Telecommunications >> Mobile Phone Flex Cables",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 53,
    CustomProperties: {},
  },
];
