export const CatalogData = [
  {
    Name: "Watch",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "watch",
    ParentCategoryId: 0,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Watch",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 17,
    CustomProperties: {},
  },
  {
    Name: "Bag",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "bag",
    ParentCategoryId: 0,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Bag",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 18,
    CustomProperties: {},
  },
  {
    Name: "Ali Express",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "ali-express",
    ParentCategoryId: 0,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: false,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 19,
    CustomProperties: {},
  },
  {
    Name: "Women's Handbags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "womens-handbags",
    ParentCategoryId: 19,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 22,
    CustomProperties: {},
  },
  {
    Name: "Waist Packs",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "waist-packs",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Waist Packs",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 23,
    CustomProperties: {},
  },
  {
    Name: "Shoulder Bags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "shoulder-bags",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Shoulder Bags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 24,
    CustomProperties: {},
  },
  {
    Name: "Messenger Bags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "messenger-bags",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Messenger Bags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 25,
    CustomProperties: {},
  },
  {
    Name: "Clutches",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "clutches",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Clutches",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 26,
    CustomProperties: {},
  },
  {
    Name: "Chest Bags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "chest-bags",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Chest Bags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 27,
    CustomProperties: {},
  },
  {
    Name: "Top-Handle Bags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "top-handle-bags",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Top-Handle Bags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 28,
    CustomProperties: {},
  },
  {
    Name: "Crossbody Bags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "crossbody-bags",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Crossbody Bags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 29,
    CustomProperties: {},
  },
  {
    Name: "Evening Bags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "evening-bags",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Evening Bags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 30,
    CustomProperties: {},
  },
  {
    Name: "Tote Bags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "tote-bags",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Tote Bags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 31,
    CustomProperties: {},
  },
  {
    Name: "Hobo Bags",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "hobo-bags",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Hobo Bags",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 32,
    CustomProperties: {},
  },
  {
    Name: "Wristlets",
    Description: null,
    CategoryTemplateId: 1,
    AvailableCategoryTemplates: [],
    MetaKeywords: null,
    MetaDescription: null,
    MetaTitle: null,
    SeName: "wristlets",
    ParentCategoryId: 22,
    PictureId: 0,
    PageSize: 6,
    AllowCustomersToSelectPageSize: true,
    PageSizeOptions: "6, 3, 9",
    PriceRangeFiltering: true,
    PriceFrom: 0,
    PriceTo: 10000,
    ManuallyPriceRange: true,
    ShowOnHomepage: false,
    IncludeInTopMenu: true,
    Published: true,
    Deleted: false,
    DisplayOrder: 0,
    Locales: [],
    Breadcrumb: "Ali Express >> Women's Handbags >> Wristlets",
    SelectedCustomerRoleIds: [],
    AvailableCustomerRoles: [],
    SelectedStoreIds: [],
    AvailableStores: [],
    AvailableCategories: [],
    SelectedDiscountIds: [],
    AvailableDiscounts: [],
    CategoryProductSearchModel: {
      CategoryId: 0,
      Page: 1,
      PageSize: 10,
      AvailablePageSizes: null,
      Draw: null,
      Start: 0,
      Length: 10,
      CustomProperties: {},
    },
    PrimaryStoreCurrencyCode: null,
    id: 33,
    CustomProperties: {},
  },
];
